#!/bin/bash

## Description: Install packages and TYPO3 (if not installed already) and set some basic configuration.
## Usage: install

composer install

test -f public/typo3conf/LocalConfiguration.php || typo3cms install:setup

typo3cms configuration:set 'EXTENSIONS/dlf/fileGrpAudio' 'AUDIO'
typo3cms configuration:set 'EXTENSIONS/dlf/fileGrpVideo' 'VIDEO,DEFAULT'
typo3cms configuration:set --json 'FE/cacheHash/requireCacheHashPresenceParameters' '["tx_dlf[id]"]'
typo3cms configuration:set 'FE/pageNotFoundOnCHashError' 0
