base: /
languages:
  -
    title: Deutsch
    enabled: true
    base: /
    typo3Language: de
    locale: de_DE
    iso-639-1: ab
    websiteTitle: ''
    navigationTitle: ''
    hreflang: ''
    direction: ''
    flag: de
    languageId: 0
  -
    title: English
    enabled: true
    base: /en
    typo3Language: default
    locale: en_US
    iso-639-1: ab
    websiteTitle: ''
    navigationTitle: ''
    hreflang: ''
    direction: ''
    fallbackType: strict
    fallbacks: ''
    flag: us
    languageId: 1
rootPageId: 1
websiteTitle: ''
