#!/bin/bash

## Description: Install packages and TYPO3 (if not installed already) and set some basic configuration.
## Usage: install
## Example: "ddev install"

if ! test -f test -f public/typo3conf/LocalConfiguration.php
then
    # create base distribution
    ddev composer create "typo3/cms-base-distribution:^11"

    # configure composer
    ddev composer config minimum-stability dev
    ddev composer config repositories.local path /var/www/extensions/*
    ddev composer config repositories.0 composer https://composer.typo3.org/

    # install general dependencies
    ddev composer require "helhum/typo3-console:^8.2"

    # install TYPO3 using web_environment settings in config.yaml
    ddev typo3cms install:setup
    ddev typo3cms install:fixfolderstructure

    # install DFG-Viewer dependencies
    ddev composer require "kitodo/presentation:@dev"
    ddev composer require "slub/slub-digitalcollections:@dev"
    ddev composer require "slub/dfgviewer:@dev"
    ddev typo3cms install:extensionsetupifpossible

    # configure dependencies
    ddev typo3cms configuration:set 'EXTENSIONS/dlf/fileGrpAudio' 'AUDIO'
    ddev typo3cms configuration:set 'EXTENSIONS/dlf/fileGrpVideo' 'VIDEO,DEFAULT'
    ddev typo3cms configuration:set --json 'FE/cacheHash/requireCacheHashPresenceParameters' '["tx_dlf[id]"]'
    ddev typo3cms configuration:set 'FE/pageNotFoundOnCHashError' 0
    ddev typo3cms configuration:set 'SYS/trustedHostsPattern' '.*'
fi



