base: /
languages:
  -
    title: Deutsch
    enabled: true
    locale: de_DE
    hreflang: ''
    base: /
    websiteTitle: ''
    navigationTitle: ''
    flag: de
    languageId: 0
  -
    title: English
    enabled: true
    locale: en-US
    hreflang: ''
    base: /en/
    websiteTitle: ''
    navigationTitle: ''
    fallbackType: strict
    fallbacks: ''
    flag: us
    languageId: 1
rootPageId: 1
websiteTitle: ''
