#!/bin/bash

## Description: Install packages and TYPO3 (if not installed already) and set some basic configuration.
## Usage: setup
## Example: "ddev setup"

composer install

test -f config/system/settings.php || typo3 install:setup

# # Other settings
typo3 configuration:set 'EXTENSIONS/dlf/fileGrpAudio' 'AUDIO'
typo3 configuration:set 'EXTENSIONS/dlf/fileGrpVideo' 'VIDEO,DEFAULT'
typo3 configuration:set --json 'FE/cacheHash/requireCacheHashPresenceParameters' '["tx_dlf[id]"]'
typo3 configuration:set 'FE/pageNotFoundOnCHashError' 0
typo3 configuration:set 'SYS/trustedHostsPattern' '.*'

