name: ddev-dfgviewer
type: typo3
docroot: public
php_version: "7.4"
webserver_type: apache-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
mariadb_version: "10.11"
mysql_version: ""
provider: default
use_dns_when_possible: true
composer_version: ""
hooks:
  # DDEV tries to write an AdditionalConfiguration.php on start, so we need
  # to make sure that the target folder exists
  pre-start:
    - exec-host: mkdir -p public/typo3conf/
web_environment:
- PATH=/var/www/html/vendor/bin:$PATH
- TYPO3_CONTEXT=Development
- TYPO3_INSTALL_DB_DRIVER=mysqli
- TYPO3_INSTALL_DB_USER=db
- TYPO3_INSTALL_DB_PASSWORD=db
- TYPO3_INSTALL_DB_HOST=db
- TYPO3_INSTALL_DB_DBNAME=db
- TYPO3_INSTALL_ADMIN_USER=admin
- TYPO3_INSTALL_ADMIN_PASSWORD=adminslub
- TYPO3_INSTALL_SITE_NAME=DFG-Viewer
- TYPO3_INSTALL_SITE_SETUP_TYPE=no
- TYPO3_INSTALL_WEB_SERVER_CONFIG=apache
